# Generated by Django 5.0.6 on 2024-05-12 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30)),
                ('car_model', models.IntegerField()),
                ('car_price', models.DecimalField(decimal_places=4, max_digits=4)),
                ('car_brand', models.CharField(choices=[('Toyo', 'Toyota'), ('Hon', 'Honda'), ('Suz', 'Suzuki')], default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=4, max_digits=4)),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.car')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=4, max_digits=4)),
                ('spendings', models.DecimalField(decimal_places=4, max_digits=4)),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='core.car')),
            ],
        ),
    ]
