# Generated by Django 5.0.6 on 2024-05-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_showroom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroom',
            name='user',
        ),
    ]
