# Generated by Django 5.0.6 on 2024-05-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_showroom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='car',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
