# Generated by Django 5.0.6 on 2024-05-13 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_remove_rating_car_delete_sale_delete_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30)),
                ('car_model', models.IntegerField()),
                ('car_price', models.DecimalField(decimal_places=4, max_digits=4)),
                ('car_brand', models.CharField(choices=[('Toyo', 'Toyota'), ('Hon', 'Honda'), ('Suz', 'Suzuki')], default=None, max_length=100)),
                ('showroom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.showroom')),
            ],
        ),
    ]
