# Generated by Django 5.0.6 on 2024-05-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_brand',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_price',
            field=models.IntegerField(),
        ),
    ]
