# Generated by Django 5.0.6 on 2024-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_car_car_brand_alter_car_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.CharField(choices=[('Hon', 'Honda'), ('Suz', 'Suzuki'), ('Toy', 'Toyota')], default=None, max_length=10),
        ),
    ]
