# Generated by Django 5.0.6 on 2024-05-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_car_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(choices=[('Hon', 'Honda'), ('Suz', 'Suzuki'), ('Toy', 'Toyota')], default=None, max_length=10, null=True),
        ),
    ]
