# Generated by Django 5.0.6 on 2024-05-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_car_car_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_brand',
        ),
    ]
