# Generated by Django 5.0.6 on 2024-05-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_car_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(choices=[('Honda', 'Honda'), ('Suzuki', 'Suuzki'), ('Toyota', 'Toyota')], default=None, max_length=10, null=True),
        ),
    ]
