# Generated by Django 5.0.6 on 2024-06-06 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_alter_car_car_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('date_purchased', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.car')),
            ],
        ),
    ]
