# Generated by Django 5.0.6 on 2024-06-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0007_alter_car_car_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='car',
        ),
        migrations.AddField(
            model_name='customer',
            name='car',
            field=models.ManyToManyField(to='inventory.car'),
        ),
    ]
