# Generated by Django 5.0.6 on 2024-06-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_car_customer_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='quantity_cars',
            field=models.IntegerField(default=0),
        ),
    ]
