# Generated by Django 5.0.6 on 2024-06-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_quantity_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='car',
            new_name='cars',
        ),
    ]
